### ISSUE TITLE
Add information on optimum layer ordering

### ISSUE THREAD

**Issue by volcan01010** [OrdnanceSurvey/OS-Open-Zoomstack-Stylesheets#1]
Please could you add information on the default layer ordering for these styles?

The [cartographic-stylesheet-user-guide](https://www.ordnancesurvey.co.uk/docs/user-guides/cartographic-stylesheet-user-guide.pdf) refers to an `_layer_order.png` file.  I found the [file for OS-OpenMap-Local](https://github.com/OrdnanceSurvey/OS-OpenMap-Local-stylesheets/blob/master/GML%20stylesheets/QGIS%20stylesheets%20(QML)/Full%20colour%20style/images/OML_layer_order.png) but cannot find an equivalent for Zoomstack.

A bullet-point list in the README.md would do the job.

**Comment by charleyglynn** [comment]
Thanks for the feedback, images now added to the relevant READMEs.

This information is also in the Getting Started Guides which can be found here: https://www.ordnancesurvey.co.uk/business-and-government/products/os-open-zoomstack.html

Cheers
Charley
