### ISSUE TITLE
Cartographic design links in READMEs are broken

### ISSUE THREAD

**Issue by flother** [OrdnanceSurvey/OS-Open-Zoomstack-Stylesheets#2]
Thanks for releasing these stylesheets as open source, they're fantastic resources.

The links to the two Ordnance Survey pages on cartographic design in the repo's various READMEs no longer work.

The first page, http://www.ordnancesurvey.co.uk/resources/carto-design/cartographic-stylesheets.html, returns HTTP 200 but the page only says "The requested URL was rejected. Please consult with your administrator."

The second page, https://www.ordnancesurvey.co.uk/resources/carto-design/, first returns HTTP 302 and redirects to https://www.ordnancesurvey.co.uk/resources/carto-design (no trailing slash). That second page returns HTTP 200 but the page only says "The page you are trying to reach has gone rambling".

**Comment by TimJMartin** [comment]
@flother we launched a new website and it would seem a few links have "gone rambling" - will pass onto our web team to get fixed.

**Comment by charleyglynn** [comment]
Our Cartographic Design Principles can now be found on GitHub: https://github.com/OrdnanceSurvey/GeoDataViz-Toolkit/tree/master/Cartographic%20Design%20Principles

Cheers
Charley

**Comment by flother** [comment]
That's great, thanks for making them available again.

FYI, the internal links within the README are broken. They link to e.g. `https://github.com/OrdnanceSurvey/GeoDataViz-Toolkit/new/master/Cartographic%20Design%20Principles#legibility` instead of just `#legibility`.

**Comment by charleyglynn** [comment]
Thanks @flother - fixed the links now.
