### ISSUE TITLE
Add default text weight to Names layer

### ISSUE THREAD

**Issue by tomchadwin** [OrdnanceSurvey/OS-Open-Zoomstack-Stylesheets#2]
It seems that emboldening of labels in the Names layer doesn't quite work as intended. This seems to be caused by the base layer label style (not the data-defined override) sometimes not setting the label "Style" correctly.

Two possible solutions:

- change the “Style” of the label of the whole layer (not the override) to Regular
- add ELSE `'Regular'` to the override

**Comment by charleyglynn** [comment]
There seems to be a difference between QGIS 3 and previous versions re how it references 'Regular'.

- QGIS 3 = 'Regular'

- QGIS 2.18.14 = 'Normal'

I have changed the override which seems to fix for QGIS 3 and also doesn't seem to effect the style in earlier versions as they default to 'Normal' anyway.
