### ISSUE TITLE
QMLs include layer customProperties which wipe Vector Tile Reader values

### ISSUE THREAD

**Issue by tomchadwin** [OrdnanceSurvey/OS-Open-Zoomstack-Stylesheets#3]
When you import Zoomstack vector tiles into QGIS, the plugin sets a few customProperties for each layer (such as the URL of the remote tile.json, if it's the hosted Zoomstack tiles). If you apply one of these QMLs to one of the layers, it wipes those customProperties.

The adverse affect this has in my specific case is to stop qgis2web working with these layers. The customProperties are how qgis2web knows a layer is a vector tiles layer, so if they are overwritten, it starts trying to export them as GeoJSON.

The simple solution is to delete the whole customProperties section from the QMLs. However, some customProperties are set in that section:

```xml
  <customproperties>
    <property value="0" key="embeddedWidgets/count"/>
    <property key="variableNames"/>
    <property key="variableValues"/>
  </customproperties>
```

They might just be default QGIS properties, in which case I think this solution is correct. However, it would be good if someone else could confirm these sections can safely be deleted. If so, I can happily do a PR.

**Comment by charleyglynn** [comment]
Hi @tomchadwin 

With a million downloads of qgis2web, this would be a great feature...if you get the time, could you please do a PR and we'll be happy to merge.

Cheers
Charley

**Comment by tomchadwin** [comment]
@charleyglynn So do you agree that what custom variables are set are simply defaults, and can all be removed?

Half a million, by the way. Unless you are saying you'd like me to wait until we hit the million mark. In which case, see you in five years.

**Comment by charleyglynn** [comment]
@tomchadwin Agreed that they're defaults and can be removed - haven't observed an issue myself after removing them.

Let's be honest, half a million is still an amazing result, the next half million might not take so long!
