### ISSUE TITLE
Colour format trick

### ISSUE THREAD

**Issue by dominijk** [OrdnanceSurvey/OS-Open-Zoomstack-Stylesheets#4]
To show hex values in markdown tables..based on your excel >

Strip the `#` off your hex put in new column then add this to the hex cell in place `=CONCATENATE("![#",G2,"](https://placehold.it/15/",G2,"/000000?text=+) `#",G2," `")`

Then copy paste the result into here for lazy markdown formatting . https://thisdavej.com/copy-table-in-excel-and-paste-as-a-markdown-table/

It will also take R,G,B values

| Feature                   | HEX code                                                            | R   | G   | B   |
|---------------------------|---------------------------------------------------------------------|-----|-----|-----|
| Country Names             | ![#55595C](https://placehold.it/15/55595C/000000?text=+) `#55595C ` | 85  | 89  | 92  |
| Capital City Names        | ![#89A489](https://placehold.it/15/89A489/000000?text=+) `#89A489 ` | 85  | 89  | 92  |
| National Park Names       | ![#55595C](https://placehold.it/15/55595C/000000?text=+) `#55595C ` | 137 | 164 | 137 |
| City Names                | ![#6A6F73](https://placehold.it/15/6A6F73/000000?text=+) `#6A6F73 ` | 85  | 89  | 92  |
| Town Names                | ![#6A6F73](https://placehold.it/15/6A6F73/000000?text=+) `#6A6F73 ` | 106 | 111 | 115 |
| Village Names             | ![#6A6F73](https://placehold.it/15/6A6F73/000000?text=+) `#6A6F73 ` | 106 | 111 | 115 |
| Suburban Names            | ![#6A6F73](https://placehold.it/15/6A6F73/000000?text=+) `#6A6F73 ` | 106 | 111 | 115 |
| Small Settlement Names    | ![#89A489](https://placehold.it/15/89A489/000000?text=+) `#89A489 ` | 106 | 111 | 115 |
| Woodland Names            | ![#6C8499](https://placehold.it/15/6C8499/000000?text=+) `#6C8499 ` | 137 | 164 | 137 |
| Water Names               | ![#6A6F73](https://placehold.it/15/6A6F73/000000?text=+) `#6A6F73 ` | 108 | 132 | 153 |
| Landcover Names           | ![#6A6F73](https://placehold.it/15/6A6F73/000000?text=+) `#6A6F73 ` | 106 | 111 | 115 |
| Landform Names            | ![#6A6F73](https://placehold.it/15/6A6F73/000000?text=+) `#6A6F73 ` | 106 | 111 | 115 |
| Sites Names               | ![#89A489](https://placehold.it/15/89A489/000000?text=+) `#89A489 ` | 106 | 111 | 115 |
| Greenspace Names          | ![#FFFFFF](https://placehold.it/15/FFFFFF/000000?text=+) `#FFFFFF ` | 137 | 164 | 137 |
| Motorway Junction Numbers | ![#9C9C9C](https://placehold.it/15/9C9C9C/000000?text=+) `#9C9C9C ` | 255 | 255 | 255 |
| Motorway Junction Box     | ![#6A6F73](https://placehold.it/15/6A6F73/000000?text=+) `#6A6F73 ` | 156 | 156 | 156 |
| Road Names                | ![#6A6F73](https://placehold.it/15/6A6F73/000000?text=+) `#6A6F73 ` | 106 | 111 | 115 |
| Road Numbers              | ![#6A6F73](https://placehold.it/15/6A6F73/000000?text=+) `#6A6F73 ` | 106 | 111 | 115 |
| Railway Station Names     | ![#6A6F73](https://placehold.it/15/6A6F73/000000?text=+) `#6A6F73 ` | 106 | 111 | 115 |
| Airport Names             | ![#6A6F73](https://placehold.it/15/6A6F73/000000?text=+) `#6A6F73 ` | 106 | 111 | 115 |
|                           |                                                                     |     |     |     |
| ETLs                      | ![#5B2F2F](https://placehold.it/15/5B2F2F/000000?text=+) `#5B2F2F ` | 91  | 47  | 47  |
| Boundaries                | ![#CFCFCF](https://placehold.it/15/CFCFCF/000000?text=+) `#CFCFCF ` | 207 | 207 | 207 |
| Buildings                 | ![#E1E0DB](https://placehold.it/15/E1E0DB/000000?text=+) `#E1E0DB ` | 225 | 224 | 219 |
| Motorways                 | ![#FFFFFF](https://placehold.it/15/FFFFFF/000000?text=+) `#FFFFFF ` | 255 | 255 | 255 |
| Primary Roads             | ![#FFFFFF](https://placehold.it/15/FFFFFF/000000?text=+) `#FFFFFF ` | 255 | 255 | 255 |
| A Roads                   | ![#FFFFFF](https://placehold.it/15/FFFFFF/000000?text=+) `#FFFFFF ` | 255 | 255 | 255 |
| B Roads                   | ![#FFFFFF](https://placehold.it/15/FFFFFF/000000?text=+) `#FFFFFF ` | 255 | 255 | 255 |
| Minor Roads               | ![#FFFFFF](https://placehold.it/15/FFFFFF/000000?text=+) `#FFFFFF ` | 255 | 255 | 255 |
| Local Roads               | ![#FFFFFF](https://placehold.it/15/FFFFFF/000000?text=+) `#FFFFFF ` | 255 | 255 | 255 |
| Restricted Roads          | ![#FFFFFF](https://placehold.it/15/FFFFFF/000000?text=+) `#FFFFFF ` | 255 | 255 | 255 |
| Road Casings              | ![#F2F0ED](https://placehold.it/15/F2F0ED/000000?text=+) `#F2F0ED ` | 242 | 240 | 237 |
| Foreshore                 | ![#E9E7E2](https://placehold.it/15/E9E7E2/000000?text=+) `#E9E7E2 ` | 233 | 231 | 226 |
| Surfacewater              | ![#C5CDD0](https://placehold.it/15/C5CDD0/000000?text=+) `#C5CDD0 ` | 197 | 205 | 208 |
| Waterlines                | ![#C5CDD0](https://placehold.it/15/C5CDD0/000000?text=+) `#C5CDD0 ` | 197 | 205 | 208 |
| Woodland                  | ![#D8DDD4](https://placehold.it/15/D8DDD4/000000?text=+) `#D8DDD4 ` | 216 | 221 | 212 |
| Greenspaces               | ![#EAEEE7](https://placehold.it/15/EAEEE7/000000?text=+) `#EAEEE7 ` | 234 | 238 | 231 |
| Sites                     | ![#EEE7DD](https://placehold.it/15/EEE7DD/000000?text=+) `#EEE7DD ` | 238 | 231 | 221 |
| Built-up Areas            | ![#E6E5E1](https://placehold.it/15/E6E5E1/000000?text=+) `#E6E5E1 ` | 230 | 229 | 225 |
| National Parks            | ![#D8DDD4](https://placehold.it/15/D8DDD4/000000?text=+) `#D8DDD4 ` | 216 | 221 | 212 |
| Sea                       | ![#C5CDD0](https://placehold.it/15/C5CDD0/000000?text=+) `#C5CDD0 ` | 197 | 205 | 208 |
| Land                      | ![#F1EFEC](https://placehold.it/15/F1EFEC/000000?text=+) `#F1EFEC ` | 241 | 239 | 236 |

**Comment by charleyglynn** [comment]
Thanks Dominic, that's great advice :+1:
