### ISSUE TITLE
Names labels not showing in QGIS 3.4 (MB Vector Tiles)

### ISSUE THREAD

**Issue by cartochris** [OrdnanceSurvey/OS-Open-Zoomstack-Stylesheets#5]
I have downloaded the MB Vector Tiles file for QGIS 3.4 and have applied the stylesheet but it appears as though the road names are not being displayed (only odd names).

They display fine in QGIS 3.2 so there must have been a change between QGIS versions for the MB tile text labelling to not display correctly?

**Comment by charleyglynn** [comment]
Hi Chris, we will have new stylesheets early in the new year so we will make sure to check this one. Thanks for the feedback :+1:
