### ISSUE TITLE
Missing icons and fonts in Mapbox

### ISSUE THREAD

**Issue by Trashmonk** [OrdnanceSurvey/OS-Open-Zoomstack-Stylesheets#6]
I have uploaded both the zoomstack mbtiles and the styles provided from this page to Mapbox. It is working very well except that none of the icons show up. I noticed that the icons provided are png while Mapbox requires svg. Furthermore when I looked into the style code I found that the style was pointing to:

    "sprite": "mapbox://sprites/geodataviz/cjh68ksxr3tbw2rol4ra78lew",
    "glyphs": "mapbox://fonts/geodataviz/{fontstack}/{range}.pbf",

However when you click on the airports layer in Mapbox it say the icon cannot be found. Are the geodataviz links still functional? Any help would be greatly appreciated.

UPDATE: I ended up finding the svg file that I needed in the QGIS stylesheets folder. It might be worthwhile moving them to the Mapbox style folder.

**Comment by charleyglynn** [comment]
Hi @Trashmonk 

Thanks so much for the feedback. We will be updating all the stylesheets soon and will make sure to include this :+1:
