### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by mzu** [OrdnanceSurvey/OS-Open-Zoomstack-Stylesheets#8]
Hi,

Is this the right place to report possible issues with spellings?

I noticed at around 54.41492988, -3.17074912 the valley is labeled as *Moasdale*. I thought this should be *Mosedale*. Are there various spellings for this? Do you get this data from OSM, since I noticed it there as well? If yes, then I am happy to fix it there.

Thanks for this great project!

**Comment by egil1978** [comment]
Hi, if you spot an issue with Ordnance Survey maps then you can email customerservices@os.uk to report this.
In this instance the spelling Moasdale is correct, however there is a small hamlet to the NE called Mosedale. Help that helps.
